### ISSUE TITLE
Error when compiling cataclysm-dda

### ISSUE THREAD

**Issue by jrrom** [leycec/raiagent#106]
Hello I am new to Gentoo so I am not sure if the problem is with the build or with my computer.

[CDDA build log](https://gist.github.com/jrrom/814566de2e1db37502a05dfb17972266)
 [Emerge info](https://gist.github.com/jrrom/1ce27aee25000c2b7cefe77c7925f736)

Regards

**Comment by jrrom** [comment]
My harfbuzz version is 5.3.1-r1

**Comment by leycec** [comment]
Welcome to the fold, young Padawan. Since this is an unofficial third-party overlay, the problem is **almost certainly with our build.** You'll quickly learn that overlays are *always* to blame. Thankfully, we're all super nice devfellows <sup>...would i lie?</sup> and delighted to promptly resolve all breakage for you.

Oh – and thanks so much for the detailed logfiles. That's always a huge help, too. :smile:

**Comment by leycec** [comment]
**Resolved by a9559d0...** *maybe.* Please let me know if you're still hitting this issue after updating; if so, we'll loudly complain to upstream on the official C:DDA issue tracker.

Until then, may the mutated zombie horde be with you always. :zombie:

**Comment by jrrom** [comment]
Thank you very much!!! I will keep the mutated zombie horde in my heart

**Comment by leycec** [comment]
**Gah!** Sadly, the prior commit failed to resolve this. Let me dig a bit deeper into the festering cesspool that is the C:DDA 0.F codebase and see if I can't scrounge together a working fix that actually works. `</sigh>`

**Comment by leycec** [comment]
**Possibly fixed yet again?** I was more... *forceful* this time. This newest patch isn't exactly ideal, but then neither is the C:DDA codebase. I pray to all the mutant zombie horde that C:DDA releases a new stable version soon! :pray: :zombie: :pray: 

Please let me know if your pain persists. Until then, hit zombies until they stop reaching for brains.

**Comment by jrrom** [comment]
Sorry it seems the stable version still doesn't build 😭 
The unstable version works perfectly though. 

Here is the log: [https://gist.github.com/jrrom/1351a3d639c4ffb693a117632943f2c6](https://gist.github.com/jrrom/1351a3d639c4ffb693a117632943f2c6)

I think you have to re-add fpermissive.

Regards

**Comment by jrrom** [comment]
How do I know if this is the latest version? I ran emerge --sync raiagent, should that be enough?

**Comment by leycec** [comment]
`emerge --sync raiagent` is exactly it. Thus, you are up-to-date and I sigh. :face_exhaling: 

Here's the five-second `tl;dr`. **Upstream is broken.** None of this is our fault, which is surprising. It's *always* our fault. In this case, however, **C:DDA 0.9F** is actually broken. This kinda makes sense. C:DDA 0.9F was released nearly two *years* ago. It's almost pre-pandemic. Clearly, C:DDA 0.9F compiled at the time just fine. But improvements to G++ (and possibly Clang has well) has ironically rendered C:DDA 0.9F uncompileable today.

Circumventing this is non-trivial, because these are fatal syntactic errors. To ignore them, it turns out that passing `-fpermissive` isn't enough; neither is stopping passing `-Werror`. You have to both pass `-fpermissive` *and* stop passing `-Werror`. But that is bad, as it silences other unrelated syntactic errors that we don't want to silence. But upstream is lazy and has failed to release a new stable version in two years... *like usual.* So, we have no choice.

`</puts_the_pencil_down>`

**Comment by jrrom** [comment]
Wow. That's horrible. Thank you so much for your time though, I will play unstable mode. This issue is like a perfect combination of bugs :( 
I guess the only fix is to wait until a new stable version comes out.

**Comment by leycec** [comment]
**Hah, hah!** It's my birthday, but you are a fellow gentleman of culture and I felt for bad for this continuing to fail. So... I've actually fixed this, *finally*. :sweat_smile: 

Please do continue to use the unstable live version of C:DDA until that inevitably breaks on you. At that point, consider reverting back to **C:DDA 0.9F stable.** Everything should now compile as expected. Bash those zombies with a homemade nail bat for @leycec.

**Comment by jrrom** [comment]
Happy Birthday!! 🎂🎂🎂

Sorry for burdening you on your birthday, I hope you're having a great time.

Thank you so much again, and goodbye
